#
# Mario Torre - 04/20/2023
#
class DynaPanelComponents(object):
    def __init__(self):
        self.api_url = None
        self.main_alert = None
        self.user_name = None
        self.password = None
        self.widget1b_title = None
        # self.db_server_name = None
        # self.db_database = None
        # self.db_driver = None
        # self.db_user_name = None
        # self.db_password = None
        self.api_connection_ok = None
        self.api_connection_ok_label = None
        self.api_token_ok = None
        self.api_token_ok_label = None
        self.db_connection_ok = None
        self.db_connection_ok_label = None
        self.api_update_button = None
        #self.db_update_button = None
        self.api_test_button = None
        # self.db_test_button = None
        self.api_update_selection_button = None
        self.api_initiate_query_button = None
        # self.save_data_button = None
        # self.save_model_button = None
        self.widget1a_title = None
        self.widget2a_title = None
        self.widget2b_title = None
        # self.widget3_title = None
        # self.widget3e_title = None
        # self.widget4a_title = None
        # self.widget4b_title = None
        # self.widget5a_title = None
        # self.widget5b_title = None
        # self.widget6a_title = None
        # self.widget6b_title = None
        self.modal_component_1 = None
        self.modal_component_2 = None
        self.upload_data_file_button = None
        self.upload_data_file_textbox = None
        self.file_dialog_1 = None
        self.file_dialog_1_ok = None
        self.file_dialog_1_cancel = None
        # self.query_format_title = None
        self.customer_selector = None
        self.asset_selector = None
        self.tag_selector = None
        self.data_table_widget = None
        # self.event_table_widget = None
        # self.model_table_widget = None
        # self.model_total_rows = None
        # self.fill_query_type = None
        # self.fill_query_type_label = None
        self.data_table1 = None
        # self.event_table1 = None
        # self.model_table = None
        # self.sampling_type = None
        # self.slice_count = None
        # self.delta_t = None
        # self.start_datetime = None
        # self.end_datatime = None
        # self.selected_tags = None
        # self.total_rows = None
        # self.total_stored_rows = None
        # self.database_name_label = None
        # self.database_table_name = None
        # self.database_create_if_inexistent = None
        # self.database_append = None
        # self.database_include_quality = None
        # self.model_database_name_label = None
        # self.model_database_table_name = None
        # self.model_total_stored_rows = None
        # self.db_initiate_store_button = None
        # db_initiate_store_events_button = None
        # self.pf_initiate_deploy_button = None
        # self.pf_show_orion_button = None
        # self.db_initiate_model_store_button = None
        # self.pf_initiate_model_deploy_button = None
        # self.pf_model_show_orion_button = None
        # self.query_url = None
        # self.operation = None
        # self.display_customer_name = None
        # self.display_customer_id = None
        # self.display_asset_name = None
        # self.display_asset_id = None
        # self.display_tag_names = None
        # self.display_tag_ids = None 
        # self.display_sampling_type = None
        # self.display_slice_count = None
        # self.display_delta_t = None
        # self.display_interval = None
        # self.display_queue_name = None
        # self.model_display_interval = None
        # self.model_display_queue_name = None
        # self.model_query_url = None
        # self.model_operation = None
        # self.model_display_customer_name = None
        # self.model_display_customer_id = None
        # self.event_start_datetime = None
        # self.event_end_datatime = None
        # self.event_total_rows = None
        # self.event_is_active = None
        # self.event_is_suppressed = None
        # self.event_is_acked = None
        # self.event_is_in_maintenance = None
        # self.event_is_disabled = None
        # self.event_is_shelved = None
        # self.event_is_active_label = None
        # self.event_is_suppressed_label = None
        # self.event_is_in_maintenance_label = None
        # self.event_is_shelved_label = None
        # self.event_query_customer_name = None
        # self.event_query_asset_name = None 
        # self.save_events_button = None
        # self.api_initiate_event_query_button = None
        # self.widget4ea_title = None
        # self.event_database_name_label = None
        # self.event_database_table_name = None
        # self.event_database_create_if_inexistent = None
        # self.event_database_append = None
        # self.event_total_stored_rows = None
        # self.widget4eb_title = None
        # self.event_query_url = None
        # self.event_operation = None
        # self.event_display_customer_name = None
        # self.event_display_customer_id = None
        # self.event_display_asset_name = None
        # self.event_display_asset_id = None
        # self.event_display_queue_name = None
        # self.event_display_interval = None
        # self.db_initiate_store_events_button =  None
        # self.pf_initiate_deploy_events_button = None
        # self.pf_show_events_orion_button = None
        # self.wb_customer_selector = None
        # self.wb_asset_selector = None
        # self.wb_tag_selector = None
        # self.wb_selected_tag = None
        # self.wb_display_tag_name = None
        # self.wb_display_tag_id = None
        # self.wb_display_tag_dataType = None
        # self.wb_display_setpoint_value = None
        # self.wb_setpoint_issue_button = None
        # #
        # # Special (not related with panel)
        # #    
        # self.export_dataframe = None
        # self.event_export_dataframe = None
        # self.model_export_dataframe = None
        